name: "Google Cloud Registry Key Parse Action"
description: "Logs into GCR and get project details using the gcloud api"
author: "Keith Hand"
runs:
  using: "node12"
  main: "main.js"
branding:
  icon: upload-cloud
  color: green
